project_id = "poster-boy-demo"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
enable_anonymous_sign_ins = true
