// CUSTOM WORD BOMB — bundled, dependency-free default English word list.
// One word per token keeps future replacement/removal straightforward.

import { normalizeWords } from './game'

const DEFAULT_WORD_SOURCE = `
ability able about above absent absorb abstract academy accept access accident account achieve acid across action active actor actress actual adapt add address adjust admire admit adopt adult advance advice afford afraid after again against age agency agenda agent agree ahead aim air alarm album alert alien alike alive allow almost alone along already also alter always amazing among amount amuse analysis ancient anger angle angry animal announce annual another answer anxiety apart apology appeal appear apple apply appoint approve april area argue arise arm army around arrange arrest arrive art artist aside ask asleep aspect assist assume athlete attack attend august aunt author auto autumn avoid awake award aware away awful
baby back badge balance ball banana band bank bar barely bargain barrel base basic basket battle beach beam bear beat beauty became because become bed before begin behave behind belief believe bell belong below belt bench benefit best better between beyond bicycle big bill bird birth bitter black blade blame blanket blind block blood blue board boat body bomb bone book border boring born borrow boss bottle bottom bowl box boy brain branch brave bread break breathe brick bridge brief bright bring broad brother brown brush build burn burst bus business busy butter button buy
cabinet cable cake call calm camera camp can canal cancel cancer candidate candle candy cap capable capital captain car card care career careful carry case cash cat catch cause ceiling celebrate cell center central century certain chain chair chance change channel chapter charge chase cheap check cheese chest chicken chief child choice choose circle city civil claim class clean clear clever click client climb clock close cloud club clue coach coast coat coffee cold collect color column combine come comfort common company compare complete concern concert condition connect consider contain content contest control cook cool copper copy corner correct cost cotton couch could count country couple course cousin cover craft crash crazy cream create credit crew crime cross crowd crucial cry culture cup curious current curve custom cut cycle
daily damage dance danger dark data daughter dawn day dead deal debate decide deep defeat defend define degree delay deliver demand deny depend desert design desk detail develop device diary dictionary die difference difficult dinner direct dirty discover discuss disease dish display distance divide doctor dog dollar door double doubt down dozen draft drag drama draw dream dress drink drive drop dry during duty
each eager early earth east easy eat echo edge edit educate effect effort egg eight either elbow elder elect element else empty end enemy energy engine enjoy enough enter entire equal error escape even event every exact example excite excuse exercise exist expect expert explain eye
face fact fail fair fall family famous fan fancy far farm fast father fault favor fear feature feed feel female fence festival fetch fever few field fight figure file fill film final find fine finger finish fire first fish fit five flag flame flat flavor flee flight floor flower fly focus fold follow food foot force forest forget fork form fortune forward found four frame free fresh friend front fruit full fun funny future
game garden gas gate gather general gentle get ghost giant gift girl give glad glass glove goal gold good govern grab grade grain grand grant grape grass great green greet ground group grow guard guess guide guitar
habit hair half hall hand handle hang happen happy hard harm hat hate have head health hear heart heat heavy help hero hide high hill hint hire history hit hold hole holiday home honest honey hope horse hospital hot hotel hour house huge human hurry hurt
ice idea identify ignore image imagine impact improve include income increase indeed index indoor industry inform inside inspire install intend interest into invite iron island issue item
jacket jail jazz job join joke journey joy judge juice jump just
keep key kick kid kill kind king kiss kitchen knee knife knock know knowledge
label labor lack ladder lake lamp land language large last late laugh launch law layer lazy lead learn least leave left leg lemon lend length lesson letter level library lie life light like limit line link lion liquid list little live local lock lonely long look loose lose loud love low loyal luck lunch
machine magic mail main major make male manage many map market marry match material matter maybe meal mean measure meat media meet member memory mention menu message metal method middle might milk million mind minute mirror miss mistake mix model modern moment money month moon more morning most mother motion mountain mouse mouth move movie much music must
name narrow nation native nature near neat necessary neck need negative neighbor nervous never new news next nice night nine noise normal north note notice novel number nurse
object ocean offer office often oil okay old once one onion online only open opinion orange order ordinary organize original other outdoor outside oven over own owner
pack page paint pair panel panic paper parent park part party pass past path patient pattern pause pay peace pen pencil people perfect period person phone photo phrase piano pick picture piece pilot pink pipe place plain plan plane plant plastic plate play player please plenty pocket point police popular position possible post potato power practice prepare present press pretty price print private prize problem process produce program project promise proof proper protect proud public pull push puzzle
quality quarter question quick quiet quite quote
radio rain raise random range rare rate rather reach react read ready real reason receive record red reduce refer relax remain remember remove repair repeat reply report rest result return rich ride right ring rise risk river road robot rock role roof room root rope rough round route rule run
safe sail salad salt same sand save scale school science score screen sea search season seat second secret section see seem select sell send sense sentence separate serious serve set seven shade shadow shake shape share sharp sheep sheet shelf shell shine ship shirt shock shoe shoot shop short should shout show side sign simple since sing sister sit six skill skin sky sleep slide slow small smart smile smoke snow social soft solid solve some song soon sorry sound south space speak special speed spell spend spider spin spirit split sport spring square stage stand star start state station stay steam steel step stick still stone stop store storm story straight strange street strong student study stuff style subject success sudden sugar summer sun support sure surprise sweet swim switch system
table take talk tall tape task taste teach team tell ten term test text than thank that theme then theory there thick thin thing think third this thought three throw ticket tidy tie tiger time tiny title today together tomato tone tool tooth top total touch tough town track trade train travel tree trick trip trouble true trust try turn twelve twice type
ugly umbrella unable uncle under unit until upper upset urban use usual
valid valley value various very video view village visit voice vote
wait wake walk wall want warm wash waste watch water wave way weak wear weather week welcome well west wet whale what wheat wheel when where which while white whole why wide wife wild will win wind window winter wire wise wish with woman wonder wood word work world worry would write wrong
yard year yellow yes young your youth zebra zero zone zoo
`

export const DEFAULT_WORDS = normalizeWords(DEFAULT_WORD_SOURCE)
